### PR TITLE
Add build flags to tune components

### PR DESCRIPTION
**Pull request by AndreyMlashkin**

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
unfortunatelly, it is forbidden to install packages via pip3 in conan CI pipeline.
https://github.com/conan-io/conan-center-index/pull/11819#issuecomment-1193852922

I need flag DILIGENT_NO_RENDER_STATE_NOTATION in order to disable building this module.
Building conan recipe with this module works fine locally... So, in the end, is only needed to pass the conan CI pipeline

**Comment by TheMostDiligent** [comment]
What is the reason to disable Imgui?

**Comment by AndreyMlashkin** [comment]
For modularity. I don't need this module for my purposes...
I can revert changes related to imgui, if you think, it is nuclear diligent-tools functionality

**Comment by TheMostDiligent** [comment]
There are dependencies between components. Just removing some component from the build will likely break other things at Diligent Engine level.

If you don't need a component, you can remove it from your build:

```CMake
set_target_properties(Diligent-Imgui PROPERTIES EXCLUDE_FROM_ALL 1 EXCLUDE_FROM_DEFAULT_BUILD 1)
```

**Comment by AndreyMlashkin** [comment]
Sounds good

**Pull request closed without merging**
