### PR TITLE
simplify conan packaging

### PR DESCRIPTION
**Pull request by AndreyMlashkin**

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
It would be also cool to have a possibility to switch off clang validation in the command:

```add_custom_command(OUTPUT ${GENERATED}
                   COMMAND ${PYTHON_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/scripts/cxx_generator.py" --dir "." --files ${REFLECTED}
                   COMMAND "${CMAKE_CURRENT_SOURCE_DIR}/../../DiligentCore/BuildTools/FormatValidation/${CLANG_FORMAT_VERSION}" -i *.hpp --verbose
                   WORKING_DIRECTORY "${RSN_PARSER_GENERATED_HEADERS_DIR}"
                   DEPENDS ${REFLECTED}
                   COMMENT "RSN Parser Header Generation")
```

**Comment by AndreyMlashkin** [comment]
I will be able to remove this patch:
https://github.com/conan-io/conan-center-index/blob/master/recipes/diligent-tools/all/patches/0010-2.5.2-fix-render-state-notation-paths.diff

**Comment by TheMostDiligent** [comment]
Merged in https://github.com/DiligentGraphics/DiligentTools/commit/e604522a83d2186f9df823515751c8034b7fb7e8

**Comment by TheMostDiligent** [comment]
> It would be also cool to have a possibility to switch off clang validation in the command:

I reworked it to check if clang-format executable exists. It should work now.

**Pull request closed without merging**
