### PR TITLE
Fix lines of code badge

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
I don't know if the problem is with shields.io, or if some repo setting is blocking it from checking, but at least the badge is showing up now.

### CODE REVIEW

**Comment by TheMostDiligent** [comment]
Yeah, the tokei service has recently been almost permanently down.
I am even considering removing the badge altogether as it almost never works.

**Comment by MichaelHinrichs** [comment]
I saw this on the Shields.io website.

> If your GitHub badge errors, it might be because you hit GitHub's rate limits. You can increase Shields.io's rate limit by [adding the Shields GitHub application](https://img.shields.io/github-auth) using your GitHub account.

**Comment by TheMostDiligent** [comment]
I tried to look through a few other repos that use the badge - it all shows unavailable for all of them

**Comment by MichaelHinrichs** [comment]
It turns out shields.io uses the same api to get the data for that badge, so it's the same problem with extra steps. I think I've found some alternative solutions tough.

**Comment by MichaelHinrichs** [comment]
ghloc
Endpoint Badge
`Endpoint Badge`
https://github.com/pajecawav/ghloc-web

sloc
Lines of code
`Lines of code`
https://sloc.xyz/github/DiligentGraphics/DiligentTools

**Comment by TheMostDiligent** [comment]
What is sloc?

**Comment by MichaelHinrichs** [comment]
Apperently it stands for "source lines of code".

**Comment by TheMostDiligent** [comment]
@MichaelHinrichs Do you know if there is a way to exclude ThirdParty directory?

**Comment by TheMostDiligent** [comment]
https://github.com/DiligentGraphics/DiligentTools/blob/master/.tokeignore

**Comment by TheMostDiligent** [comment]
The [documentation says](https://github.com/boyter/scc?tab=readme-ov-file#ignore-files) `.ignore` file can be used, but it does not seem to work.

**Comment by MichaelHinrichs** [comment]
Would you prefer to use ghloc instead?

**Comment by TheMostDiligent** [comment]
ghloc does not seem to support ignore files. Also, it is very scarcely used as opposed to sloc, so I will stick with sloc for now.

**Comment by TheMostDiligent** [comment]
Completed in 59f3c00d18852c77911407e040099b9f5d34d1b7 and 17c77de9ccf6af42827eb9eab61bc2bf75689375

**Pull request closed without merging**
